swagger: '2.0'
info:
  description: The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
  version: 1.1.1
  title: RNI API
  license:
    name: ETSI Forge copyright notice
    url: 'https://forge.etsi.org/etsi-forge-copyright-notice.txt'
externalDocs:
  description: ETSI GS MEC012 Radio Network Information API, V1.1.1
  url: 'http://www.etsi.org/deliver/etsi_gs/MEC/001_099/012/01.01.01_60/gs_mec012v010101p.pdf'
host: '127.0.0.1:8080'
basePath: /rni/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
security:
  - OauthSecurity:
      - all
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: application
    tokenUrl: 'https://oauth.exampleAPI/token'
    scopes:
      all: Single oauth2 scope for API
parameters:
  Query.AppInsIdArr:
    name: app_ins_id
    in: query
    description: Application instance identifier
    required: true
    type: array
    items:
      type: string
      
paths:
  /queries/plmn_info:
    get:
      description: >-
        Gets the information on Mobile Network(s) that are associated with a
        specific mobile edge application instance
      operationId: plmn_infoGET
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Query.AppInsIdArr'
      responses:
        '200':
          description: Successful response to rab_info request
          schema:
            type: object
            properties:
              PlmnInfo:
                $ref: '#/definitions/PlmnInfo'
          examples:
            application/json:
              PlmnInfo:
                timeStamp:
                  seconds: 1577836800
                  nanoSeconds: 0
                appInId: '01'
                ecgi:
                  plmn:
                    mcc: '001'
                    mnc: '01'
                  cellId: '0x800000A'
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '403':
          description: Forbidden
          schema:
            type: object
            required:
              - ProblemDetails
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not Found
          schema:
            type: object
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '406':
          description: Not Acceptable
          schema:
            type: object
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '429':
          description: Too Many Requests
          schema:
            type: object
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
      x-swagger-router-controller: Default
 
 
definitions:
  ProblemDetails:
    type: object
    properties:
      type:
        $ref: '#/definitions/Problem.type'
      title:
        $ref: '#/definitions/Problem.title'
      status:
        $ref: '#/definitions/Problem.status'
      detail:
        $ref: '#/definitions/Problem.detail'
      instance:
        $ref: '#/definitions/Problem.instance'
  Problem.type:
    type: string
    format: uri
    description: >-
      A URI reference according to IETF RFC 3986 that identifies the problem type
  Problem.title:
    type: string
    description: >-
      A short, human-readable summary of the problem type
  Problem.status:
    type: integer
    format: uint32
    description: >-
      The HTTP status code for this occurrence of the problem
  Problem.detail:
    type: string
    description: >-
      A human-readable explanation specific to this occurrence of the problem
  Problem.instance:
    type: string
    format: uri
    description: >-
      A URI reference that identifies the specific occurrence of the problem
  PlmnInfo:
    type: object
    required:
      - appInsId
      - ecgi
    properties:
      timeStamp:
        $ref: '#/definitions/TimeStamp'
      appInsId:
        $ref: '#/definitions/AppInsId'
      ecgi:
        $ref: '#/definitions/Ecgi' 
 
 
  TimeStamp:
    type: object
    required:
      - nanoSeconds
      - seconds
    properties:
      seconds:
        type: integer
        format: uint32
        description: >-
          The seconds part of the time. Time is defined as Unix-time since
          January 1, 1970, 00:00:00 UTC
        example: 1577836800
      nanoSeconds:
        type: integer
        format: uint32
        description: >-
          The nanoseconds part of the time. Time is defined as Unix-time since
          January 1, 1970, 00:00:00 UTC
        example: 0
 
  AppInsId:
    type: string
    format: string
    description: Unique identifier for the mobile edge application instance
    example: '01'
    
  Ecgi:
    type: object
    required:
      - cellId
      - plmn
    properties:
      plmn:
        $ref: '#/definitions/Plmn'
      cellId:
        $ref: '#/definitions/CellId'
    description: E-UTRAN CelI Global Identifier as defined in 3GPP TS 36.413 
 
  Plmn:
    type: object
    required:
      - mcc
      - mnc
    properties:
      mcc:
        type: string
        format: string
        description: >-
          The Mobile Country Code part of PLMN Identity as defined in 3GPP TS
          36.413
        example: '001'
      mnc:
        type: string
        format: string
        description: >-
          The Mobile Network Code part of PLMN Identity as defined in 3GPP TS
          36.413
        example: '01' 
 
  CellId:
    type: array
    items:
      type: string
      format: binary
    description: >-
      The E-UTRAN Cell Identity as a bit string (size (28)), as defined in 3GPP
      TS 36.413
    example: '0x800000A' 