/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CaReConfSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CaReConfSubscription::CaReConfSubscription()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

CaReConfSubscription::~CaReConfSubscription()
{
}

void CaReConfSubscription::validate()
{
    // TODO: implement validation
}

nlohmann::json CaReConfSubscription::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["_links"] = ModelBase::toJson(m__links);
    val["filterCriteria"] = ModelBase::toJson(m_FilterCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void CaReConfSubscription::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string CaReConfSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void CaReConfSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link CaReConfSubscription::getLinks() const
{
    return m__links;
}
void CaReConfSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
FilterCriteriaAssoc CaReConfSubscription::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void CaReConfSubscription::setFilterCriteria(FilterCriteriaAssoc const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp CaReConfSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void CaReConfSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool CaReConfSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void CaReConfSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}
}

