/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Ecgi.h
 *
 * E-UTRAN CelI Global Identifier as defined in 3GPP TS 36.413
 */

#ifndef Ecgi_H_
#define Ecgi_H_


#include "ModelBase.h"

#include "Plmn.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// E-UTRAN CelI Global Identifier as defined in 3GPP TS 36.413
/// </summary>
class  Ecgi
    : public ModelBase
{
public:
    Ecgi();
    virtual ~Ecgi();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Ecgi members

    /// <summary>
    /// 
    /// </summary>
    Plmn getPlmn() const;
    void setPlmn(Plmn const& value);
        /// <summary>
    /// The E-UTRAN Cell Identity as a bit string (size (28)), as defined in 3GPP TS 36.413
    /// </summary>
    std::vector<std::string>& getCellId();
    
protected:
    Plmn m_Plmn;

    std::vector<std::string> m_CellId;

};

}
}
}
}

#endif /* Ecgi_H_ */
