/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_12.h
 *
 * 
 */

#ifndef Inline_object_12_H_
#define Inline_object_12_H_


#include "ModelBase.h"

#include "RabRelSubscriptionPost.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_12
    : public ModelBase
{
public:
    Inline_object_12();
    virtual ~Inline_object_12();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_object_12 members

    /// <summary>
    /// 
    /// </summary>
    RabRelSubscriptionPost getRabRelSubscription() const;
    void setRabRelSubscription(RabRelSubscriptionPost const& value);
    bool rabRelSubscriptionIsSet() const;
    void unsetRabRelSubscription();

protected:
    RabRelSubscriptionPost m_RabRelSubscription;
    bool m_RabRelSubscriptionIsSet;
};

}
}
}
}

#endif /* Inline_object_12_H_ */
