/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineResponse403.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_403::Inline_response_403()
{
    
}

Inline_response_403::~Inline_response_403()
{
}

void Inline_response_403::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_response_403::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["ProblemDetails"] = ModelBase::toJson(m_ProblemDetails);
    

    return val;
}

void Inline_response_403::fromJson(const nlohmann::json& val)
{
    
}


ProblemDetails Inline_response_403::getProblemDetails() const
{
    return m_ProblemDetails;
}
void Inline_response_403::setProblemDetails(ProblemDetails const& value)
{
    m_ProblemDetails = value;
    
}

}
}
}
}

