/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineObject12.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_12::Inline_object_12()
{
    m_RabRelSubscriptionIsSet = false;
    
}

Inline_object_12::~Inline_object_12()
{
}

void Inline_object_12::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_object_12::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_RabRelSubscriptionIsSet)
    {
        val["RabRelSubscription"] = ModelBase::toJson(m_RabRelSubscription);
    }
    

    return val;
}

void Inline_object_12::fromJson(const nlohmann::json& val)
{
    if(val.find("RabRelSubscription") != val.end())
    {
        if(!val["RabRelSubscription"].is_null())
        {
            RabRelSubscriptionPost newItem;
            newItem.fromJson(val["RabRelSubscription"]);
            setRabRelSubscription( newItem );
        }
        
    }
    
}


RabRelSubscriptionPost Inline_object_12::getRabRelSubscription() const
{
    return m_RabRelSubscription;
}
void Inline_object_12::setRabRelSubscription(RabRelSubscriptionPost const& value)
{
    m_RabRelSubscription = value;
    m_RabRelSubscriptionIsSet = true;
}
bool Inline_object_12::rabRelSubscriptionIsSet() const
{
    return m_RabRelSubscriptionIsSet;
}
void Inline_object_12::unsetRabRelSubscription()
{
    m_RabRelSubscriptionIsSet = false;
}

}
}
}
}

