/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_3.h
 *
 * 
 */

#ifndef Inline_object_3_H_
#define Inline_object_3_H_


#include "ModelBase.h"

#include "S1BearerSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_3
    : public ModelBase
{
public:
    Inline_object_3();
    virtual ~Inline_object_3();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_object_3 members

    /// <summary>
    /// 
    /// </summary>
    S1BearerSubscription getS1BearerSubscription() const;
    void setS1BearerSubscription(S1BearerSubscription const& value);
    bool s1BearerSubscriptionIsSet() const;
    void unsetS1BearerSubscription();

protected:
    S1BearerSubscription m_S1BearerSubscription;
    bool m_S1BearerSubscriptionIsSet;
};

}
}
}
}

#endif /* Inline_object_3_H_ */
