/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineResponse2002.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_2::Inline_response_200_2()
{
    
}

Inline_response_200_2::~Inline_response_200_2()
{
}

void Inline_response_200_2::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_response_200_2::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["S1BearerInfo"] = ModelBase::toJson(m_S1BearerInfo);
    

    return val;
}

void Inline_response_200_2::fromJson(const nlohmann::json& val)
{
    
}


S1BearerInfo Inline_response_200_2::getS1BearerInfo() const
{
    return m_S1BearerInfo;
}
void Inline_response_200_2::setS1BearerInfo(S1BearerInfo const& value)
{
    m_S1BearerInfo = value;
    
}

}
}
}
}

