/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineResponse2015.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_201_5::Inline_response_201_5()
{
    m_RabModSubscriptionIsSet = false;
    
}

Inline_response_201_5::~Inline_response_201_5()
{
}

void Inline_response_201_5::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_response_201_5::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_RabModSubscriptionIsSet)
    {
        val["RabModSubscription"] = ModelBase::toJson(m_RabModSubscription);
    }
    

    return val;
}

void Inline_response_201_5::fromJson(const nlohmann::json& val)
{
    if(val.find("RabModSubscription") != val.end())
    {
        if(!val["RabModSubscription"].is_null())
        {
            RabModSubscription newItem;
            newItem.fromJson(val["RabModSubscription"]);
            setRabModSubscription( newItem );
        }
        
    }
    
}


RabModSubscription Inline_response_201_5::getRabModSubscription() const
{
    return m_RabModSubscription;
}
void Inline_response_201_5::setRabModSubscription(RabModSubscription const& value)
{
    m_RabModSubscription = value;
    m_RabModSubscriptionIsSet = true;
}
bool Inline_response_201_5::rabModSubscriptionIsSet() const
{
    return m_RabModSubscriptionIsSet;
}
void Inline_response_201_5::unsetRabModSubscription()
{
    m_RabModSubscriptionIsSet = false;
}

}
}
}
}

