/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineObject6.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_6::Inline_object_6()
{
    m_MeasRepUeSubscriptionIsSet = false;
    
}

Inline_object_6::~Inline_object_6()
{
}

void Inline_object_6::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_object_6::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_MeasRepUeSubscriptionIsSet)
    {
        val["MeasRepUeSubscription"] = ModelBase::toJson(m_MeasRepUeSubscription);
    }
    

    return val;
}

void Inline_object_6::fromJson(const nlohmann::json& val)
{
    if(val.find("MeasRepUeSubscription") != val.end())
    {
        if(!val["MeasRepUeSubscription"].is_null())
        {
            MeasRepUeSubscriptionPost newItem;
            newItem.fromJson(val["MeasRepUeSubscription"]);
            setMeasRepUeSubscription( newItem );
        }
        
    }
    
}


MeasRepUeSubscriptionPost Inline_object_6::getMeasRepUeSubscription() const
{
    return m_MeasRepUeSubscription;
}
void Inline_object_6::setMeasRepUeSubscription(MeasRepUeSubscriptionPost const& value)
{
    m_MeasRepUeSubscription = value;
    m_MeasRepUeSubscriptionIsSet = true;
}
bool Inline_object_6::measRepUeSubscriptionIsSet() const
{
    return m_MeasRepUeSubscriptionIsSet;
}
void Inline_object_6::unsetMeasRepUeSubscription()
{
    m_MeasRepUeSubscriptionIsSet = false;
}

}
}
}
}

