/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "MeasRepUeSubscriptionPost.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

MeasRepUeSubscriptionPost::MeasRepUeSubscriptionPost()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

MeasRepUeSubscriptionPost::~MeasRepUeSubscriptionPost()
{
}

void MeasRepUeSubscriptionPost::validate()
{
    // TODO: implement validation
}

nlohmann::json MeasRepUeSubscriptionPost::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["filterCriteria"] = ModelBase::toJson(m_FilterCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void MeasRepUeSubscriptionPost::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string MeasRepUeSubscriptionPost::getCallbackReference() const
{
    return m_CallbackReference;
}
void MeasRepUeSubscriptionPost::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
FilterCriteriaAssocTri MeasRepUeSubscriptionPost::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void MeasRepUeSubscriptionPost::setFilterCriteria(FilterCriteriaAssocTri const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp MeasRepUeSubscriptionPost::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void MeasRepUeSubscriptionPost::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool MeasRepUeSubscriptionPost::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void MeasRepUeSubscriptionPost::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}
}

