/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Plmn.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Plmn::Plmn()
{
    m_Mcc = "";
    m_Mnc = "";
    
}

Plmn::~Plmn()
{
}

void Plmn::validate()
{
    // TODO: implement validation
}

nlohmann::json Plmn::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mcc"] = ModelBase::toJson(m_Mcc);
    val["mnc"] = ModelBase::toJson(m_Mnc);
    

    return val;
}

void Plmn::fromJson(const nlohmann::json& val)
{
    setMcc(val.at("mcc"));
    setMnc(val.at("mnc"));
    
}


std::string Plmn::getMcc() const
{
    return m_Mcc;
}
void Plmn::setMcc(std::string const& value)
{
    m_Mcc = value;
    
}
std::string Plmn::getMnc() const
{
    return m_Mnc;
}
void Plmn::setMnc(std::string const& value)
{
    m_Mnc = value;
    
}

}
}
}
}

