/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TempUeId.h
 *
 * 
 */

#ifndef TempUeId_H_
#define TempUeId_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  TempUeId
    : public ModelBase
{
public:
    TempUeId();
    virtual ~TempUeId();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// TempUeId members

    /// <summary>
    /// MMEC as defined in ETSI TS 136 413
    /// </summary>
    std::string getMmec() const;
    void setMmec(std::string const& value);
        /// <summary>
    /// M-TMSI as defined in ETSI TS 136 413
    /// </summary>
    std::string getMtmsi() const;
    void setMtmsi(std::string const& value);
    
protected:
    std::string m_Mmec;

    std::string m_Mtmsi;

};

}
}
}
}

#endif /* TempUeId_H_ */
