/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AppTerminationNotificationSubscription.h"

namespace llmec {
namespace mp1 {
namespace model {

AppTerminationNotificationSubscription::AppTerminationNotificationSubscription(): NotificationSubscription()
{
	//NotificationSubscription();
    //m_SubscriptionType = "";
    //m_CallbackReference = "";
    m_AppInstanceId = "";
    
}

AppTerminationNotificationSubscription::~AppTerminationNotificationSubscription()
{
}
/*
void AppTerminationNotificationSubscription::validate()
{
    // TODO: implement validation
}
*/
void to_json(nlohmann::json& j, const AppTerminationNotificationSubscription& o)
{
    j = nlohmann::json();
    j["subscriptionType"] = o.m_SubscriptionType;
    j["callbackReference"] = o.m_CallbackReference;
    j["_links"] = o.m__links;
    j["appInstanceId"] = o.m_AppInstanceId;
}

void from_json(const nlohmann::json& j, AppTerminationNotificationSubscription& o)
{
    j.at("subscriptionType").get_to(o.m_SubscriptionType);
    j.at("callbackReference").get_to(o.m_CallbackReference);
    j.at("_links").get_to(o.m__links);
    j.at("appInstanceId").get_to(o.m_AppInstanceId);
}
/*
std::string AppTerminationNotificationSubscription::getSubscriptionType() const
{
    return m_SubscriptionType;
}
void AppTerminationNotificationSubscription::setSubscriptionType(std::string const& value)
{
    m_SubscriptionType = value;
    
}
std::string AppTerminationNotificationSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void AppTerminationNotificationSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Self AppTerminationNotificationSubscription::getLinks() const
{
    return m__links;
}
void AppTerminationNotificationSubscription::setLinks(Self const& value)
{
    m__links = value;
    
}
*/
std::string AppTerminationNotificationSubscription::getAppInstanceId() const
{
    return m_AppInstanceId;
}
void AppTerminationNotificationSubscription::setAppInstanceId(std::string const& value)
{
    m_AppInstanceId = value;
    
}

}
}
}

