/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AppTerminationNotification.h
 *
 * This type represents the information that the mobile edge platform notifies the subscribed application instance about  the corresponding application instance termination/stop.
 */

#ifndef AppTerminationNotification_H_
#define AppTerminationNotification_H_


#include <string>
#include "Subscription.h"
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// This type represents the information that the mobile edge platform notifies the subscribed application instance about  the corresponding application instance termination/stop.
/// </summary>
class  AppTerminationNotification
{
public:
    AppTerminationNotification();
    virtual ~AppTerminationNotification();

    void validate();

    /////////////////////////////////////////////
    /// AppTerminationNotification members

    /// <summary>
    /// Shall be set to AppTerminationNotification.
    /// </summary>
    std::string getNotificationType() const;
    void setNotificationType(std::string const& value);
        /// <summary>
    /// Maximum timeout value in seconds for graceful termination or graceful stop of an application instance.
    /// </summary>
    int32_t getMaxGracefulTimeout() const;
    void setMaxGracefulTimeout(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    Subscription getLinks() const;
    void setLinks(Subscription const& value);
    
    friend void to_json(nlohmann::json& j, const AppTerminationNotification& o);
    friend void from_json(const nlohmann::json& j, AppTerminationNotification& o);
protected:
    std::string m_NotificationType;

    int32_t m_MaxGracefulTimeout;

    Subscription m__links;

};

}
}
}

#endif /* AppTerminationNotification_H_ */
