/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AssociateId.h
 *
 * 
 */

#ifndef AssociateId_H_
#define AssociateId_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AssociateId
    : public ModelBase
{
public:
    AssociateId();
    virtual ~AssociateId();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AssociateId members

    /// <summary>
    /// Numeric value (0-255) corresponding to specified type of identifier
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);
        /// <summary>
    /// Value for the identifier
    /// </summary>
    std::string getValue() const;
    void setValue(std::string const& value);
    
protected:
    std::string m_Type;

    std::string m_Value;

};

}
}
}
}

#endif /* AssociateId_H_ */
