/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CaReConfSubscriptionPost.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

CaReConfSubscriptionPost::CaReConfSubscriptionPost()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

CaReConfSubscriptionPost::~CaReConfSubscriptionPost()
{
}

void CaReConfSubscriptionPost::validate()
{
    // TODO: implement validation
}

nlohmann::json CaReConfSubscriptionPost::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["filterCriteria"] = ModelBase::toJson(m_FilterCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void CaReConfSubscriptionPost::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string CaReConfSubscriptionPost::getCallbackReference() const
{
    return m_CallbackReference;
}
void CaReConfSubscriptionPost::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
FilterCriteriaAssoc CaReConfSubscriptionPost::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void CaReConfSubscriptionPost::setFilterCriteria(FilterCriteriaAssoc const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp CaReConfSubscriptionPost::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void CaReConfSubscriptionPost::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool CaReConfSubscriptionPost::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void CaReConfSubscriptionPost::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}
}

