/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CaReConfSubscription.h"

namespace llmec {
namespace mp1 {
namespace model {

CaReConfSubscription::CaReConfSubscription()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

CaReConfSubscription::~CaReConfSubscription()
{
}

void CaReConfSubscription::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const CaReConfSubscription& o)
{
    j = nlohmann::json();
    j["callbackReference"] = o.m_CallbackReference;
    j["_links"] = o.m__links;
    j["filterCriteria"] = o.m_FilterCriteria;
    if(o.expiryDeadlineIsSet())
        j["expiryDeadline"] = o.m_ExpiryDeadline;
}

void from_json(const nlohmann::json& j, CaReConfSubscription& o)
{
    j.at("callbackReference").get_to(o.m_CallbackReference);
    j.at("_links").get_to(o.m__links);
    j.at("filterCriteria").get_to(o.m_FilterCriteria);
    if(j.contains("expiryDeadline"))
    {
        j.at("expiryDeadline").get_to(o.m_ExpiryDeadline);
        o.m_ExpiryDeadlineIsSet = true;
    } 
}

std::string CaReConfSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void CaReConfSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link CaReConfSubscription::getLinks() const
{
    return m__links;
}
void CaReConfSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
FilterCriteriaAssoc CaReConfSubscription::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void CaReConfSubscription::setFilterCriteria(FilterCriteriaAssoc const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp CaReConfSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void CaReConfSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool CaReConfSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void CaReConfSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}

