/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CellUserInfo.h"

namespace llmec {
namespace mp1 {
namespace model {

CellUserInfo::CellUserInfo()
{
    
}

CellUserInfo::~CellUserInfo()
{
}

void CellUserInfo::validate()
{
    // TODO: implement validation
}

nlohmann::json CellUserInfo::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["ecgi"] = ModelBase::toJson(m_Ecgi);
    {
        nlohmann::json jsonArray;
        for( const auto& item : m_UeInfo )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["ueInfo"] = jsonArray;
        
    }
    

    return val;
}

void CellUserInfo::fromJson(const nlohmann::json& val)
{
    {
        m_UeInfo.clear();
                    for( const auto& item : val["ueInfo"] )
            {
                
                if(item.is_null())
                {
                    m_UeInfo.push_back( UeInfo() );
                }
                else
                {
                    UeInfo newItem;
                    newItem.fromJson(item);
                    m_UeInfo.push_back( newItem );
                }
                
            }
    }
    
}


Ecgi CellUserInfo::getEcgi() const
{
    return m_Ecgi;
}
void CellUserInfo::setEcgi(Ecgi const& value)
{
    m_Ecgi = value;
    
}
std::vector<UeInfo>& CellUserInfo::getUeInfo()
{
    return m_UeInfo;
}

}
}
}

