/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CellChangeSubscriptionPost.h"

namespace llmec {
namespace mp1 {
namespace model {

CellChangeSubscriptionPost::CellChangeSubscriptionPost()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

CellChangeSubscriptionPost::~CellChangeSubscriptionPost()
{
}

void CellChangeSubscriptionPost::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const CellChangeSubscriptionPost& o)
{
    j = nlohmann::json();
    j["callbackReference"] = o.m_CallbackReference;
    j["filterCriteria"] = o.m_FilterCriteria;
    if(o.expiryDeadlineIsSet())
        j["expiryDeadline"] = o.m_ExpiryDeadline;
}

void from_json(const nlohmann::json& j, CellChangeSubscriptionPost& o)
{
    j.at("callbackReference").get_to(o.m_CallbackReference);
    j.at("filterCriteria").get_to(o.m_FilterCriteria);
    if(j.contains("expiryDeadline"))
    {
        j.at("expiryDeadline").get_to(o.m_ExpiryDeadline);
        o.m_ExpiryDeadlineIsSet = true;
    } 
}

std::string CellChangeSubscriptionPost::getCallbackReference() const
{
    return m_CallbackReference;
}
void CellChangeSubscriptionPost::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
FilterCriteriaAssocHo CellChangeSubscriptionPost::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void CellChangeSubscriptionPost::setFilterCriteria(FilterCriteriaAssocHo const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp CellChangeSubscriptionPost::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void CellChangeSubscriptionPost::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool CellChangeSubscriptionPost::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void CellChangeSubscriptionPost::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}

