/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Ecgi.h"

namespace llmec {
namespace mp1 {
namespace model {

Ecgi::Ecgi()
{
    
}

Ecgi::~Ecgi()
{
}

void Ecgi::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Ecgi& o)
{
    j = nlohmann::json();
    j["plmn"] = o.m_Plmn;
    j["cellId"] = o.m_CellId;
}

void from_json(const nlohmann::json& j, Ecgi& o)
{
    j.at("plmn").get_to(o.m_Plmn);
    j.at("cellId").get_to(o.m_CellId);
}

Plmn Ecgi::getPlmn() const
{
    return m_Plmn;
}
void Ecgi::setPlmn(Plmn const& value)
{
    m_Plmn = value;
    
}
std::vector<std::string>& Ecgi::getCellId()
{
    return m_CellId;
}

}
}
}

