/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EndPointInfo_Address.h
 *
 * A IP address and port pair
 */

#ifndef EndPointInfo_Address_H_
#define EndPointInfo_Address_H_


#include <string>
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// A IP address and port pair
/// </summary>
class  EndPointInfo_Address
{
public:
    EndPointInfo_Address();
    virtual ~EndPointInfo_Address();

    void validate();

    /////////////////////////////////////////////
    /// EndPointInfo_Address members

    /// <summary>
    /// Host portion of the address
    /// </summary>
    std::string getHost() const;
    void setHost(std::string const& value);
        /// <summary>
    /// Port portion of the address
    /// </summary>
    int32_t getPort() const;
    void setPort(int32_t const value);
    
    friend void to_json(nlohmann::json& j, const EndPointInfo_Address& o);
    friend void from_json(const nlohmann::json& j, EndPointInfo_Address& o);
protected:
    std::string m_Host;

    int32_t m_Port;

};

}
}
}

#endif /* EndPointInfo_Address_H_ */
