/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ErabQosParameters.h"

namespace llmec {
namespace mp1 {
namespace model {

ErabQosParameters::ErabQosParameters()
{
    m_Qci = 0;
    m_QciIsSet = false;
    m_Qos_informationIsSet = false;
    
}

ErabQosParameters::~ErabQosParameters()
{
}

void ErabQosParameters::validate()
{
    // TODO: implement validation
}

nlohmann::json ErabQosParameters::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_QciIsSet)
    {
        val["qci"] = m_Qci;
    }
    if(m_Qos_informationIsSet)
    {
        val["qos_information"] = ModelBase::toJson(m_Qos_information);
    }
    

    return val;
}

void ErabQosParameters::fromJson(const nlohmann::json& val)
{
    if(val.find("qci") != val.end())
    {
        setQci(val.at("qci"));
    }
    if(val.find("qos_information") != val.end())
    {
        if(!val["qos_information"].is_null())
        {
            QosInformation newItem;
            newItem.fromJson(val["qos_information"]);
            setQosInformation( newItem );
        }
        
    }
    
}


int32_t ErabQosParameters::getQci() const
{
    return m_Qci;
}
void ErabQosParameters::setQci(int32_t const value)
{
    m_Qci = value;
    m_QciIsSet = true;
}
bool ErabQosParameters::qciIsSet() const
{
    return m_QciIsSet;
}
void ErabQosParameters::unsetQci()
{
    m_QciIsSet = false;
}
QosInformation ErabQosParameters::getQosInformation() const
{
    return m_Qos_information;
}
void ErabQosParameters::setQosInformation(QosInformation const& value)
{
    m_Qos_information = value;
    m_Qos_informationIsSet = true;
}
bool ErabQosParameters::qosInformationIsSet() const
{
    return m_Qos_informationIsSet;
}
void ErabQosParameters::unsetQos_information()
{
    m_Qos_informationIsSet = false;
}

}
}
}

