/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ErabQosParameters_qci.h
 *
 * QoS Class Identifier as defined in TS 23.401
 */

#ifndef ErabQosParameters_qci_H_
#define ErabQosParameters_qci_H_


#include "ModelBase.h"

#include "QosInformation.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// QoS Class Identifier as defined in TS 23.401
/// </summary>
class  ErabQosParameters_qci
    : public ModelBase
{
public:
    ErabQosParameters_qci();
    virtual ~ErabQosParameters_qci();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ErabQosParameters_qci members

    /// <summary>
    /// 
    /// </summary>
    QosInformation getQosInformation() const;
    void setQosInformation(QosInformation const& value);
    bool qosInformationIsSet() const;
    void unsetQosInformation();

protected:
    QosInformation m_QosInformation;
    bool m_QosInformationIsSet;
};

}
}
}

#endif /* ErabQosParameters_qci_H_ */
