/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EventType.h
 *
 * Description of the subscribed event.
 */

#ifndef EventType_H_
#define EventType_H_


#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// Description of the subscribed event.
/// </summary>
class  EventType
{
public:
    EventType();
    virtual ~EventType();

    void validate();

    /////////////////////////////////////////////
    /// EventType members


    friend void to_json(nlohmann::json& j, const EventType& o);
    friend void from_json(const nlohmann::json& j, EventType& o);
protected:
};

}
}
}

#endif /* EventType_H_ */
