/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * FilterCriteriaAssocQci.h
 *
 * List of filtering criteria for the subscription.
 */

#ifndef FilterCriteriaAssocQci_H_
#define FilterCriteriaAssocQci_H_


#include "Plmn.h"
#include <string>
#include "AssociateId.h"
#include <vector>
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// List of filtering criteria for the subscription.
/// </summary>
class  FilterCriteriaAssocQci
{
public:
    FilterCriteriaAssocQci();
    virtual ~FilterCriteriaAssocQci();

    void validate();

    /////////////////////////////////////////////
    /// FilterCriteriaAssocQci members

    /// <summary>
    /// Unique identifier for the mobile edge application instance
    /// </summary>
    std::string getAppInsId() const;
    void setAppInsId(std::string const& value);
    bool appInsIdIsSet() const;
    void unsetAppInsId();
    /// <summary>
    /// 
    /// </summary>
    AssociateId getAssociateId() const;
    void setAssociateId(AssociateId const& value);
    bool associateIdIsSet() const;
    void unsetAssociateId();
    /// <summary>
    /// 
    /// </summary>
    Plmn getPlmn() const;
    void setPlmn(Plmn const& value);
    bool plmnIsSet() const;
    void unsetPlmn();
    /// <summary>
    /// The E-UTRAN Cell Identity as a bit string (size (28)), as defined in 3GPP TS 36.413
    /// </summary>
    std::vector<std::string>& getCellId();
    bool cellIdIsSet() const;
    void unsetCellId();
    /// <summary>
    /// QoS Class Identifier as defined in TS 23.401
    /// </summary>
    int32_t getQci() const;
    void setQci(int32_t const value);
    bool qciIsSet() const;
    void unsetQci();

    friend void to_json(nlohmann::json& j, const FilterCriteriaAssocQci& o);
    friend void from_json(const nlohmann::json& j, FilterCriteriaAssocQci& o);
protected:
    std::string m_AppInsId;
    bool m_AppInsIdIsSet;
    AssociateId m_AssociateId;
    bool m_AssociateIdIsSet;
    Plmn m_Plmn;
    bool m_PlmnIsSet;
    std::vector<std::string> m_CellId;
    bool m_CellIdIsSet;
    int32_t m_Qci;
    bool m_QciIsSet;
};

}
}
}

#endif /* FilterCriteriaAssocQci_H_ */
