/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "FilterCriteriaAssocHo.h"

namespace llmec {
namespace mp1 {
namespace model {

FilterCriteriaAssocHo::FilterCriteriaAssocHo()
{
    m_AppInsId = "";
    m_AppInsIdIsSet = false;
    m_AssociateIdIsSet = false;
    m_PlmnIsSet = false;
    m_CellIdIsSet = false;
    m_HoStatusIsSet = false;
    
}

FilterCriteriaAssocHo::~FilterCriteriaAssocHo()
{
}

void FilterCriteriaAssocHo::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const FilterCriteriaAssocHo& o)
{
    j = nlohmann::json();
    if(o.appInsIdIsSet())
        j["appInsId"] = o.m_AppInsId;
    if(o.associateIdIsSet())
        j["associateId"] = o.m_AssociateId;
    if(o.plmnIsSet())
        j["plmn"] = o.m_Plmn;
    if(o.cellIdIsSet())
        j["cellId"] = o.m_CellId;
    if(o.hoStatusIsSet())
        j["hoStatus"] = o.m_HoStatus;
}

void from_json(const nlohmann::json& j, FilterCriteriaAssocHo& o)
{
    if(j.contains("appInsId"))
    {
        j.at("appInsId").get_to(o.m_AppInsId);
        o.m_AppInsIdIsSet = true;
    } 
    if(j.contains("associateId"))
    {
        j.at("associateId").get_to(o.m_AssociateId);
        o.m_AssociateIdIsSet = true;
    } 
    if(j.contains("plmn"))
    {
        j.at("plmn").get_to(o.m_Plmn);
        o.m_PlmnIsSet = true;
    } 
    if(j.contains("cellId"))
    {
        j.at("cellId").get_to(o.m_CellId);
        o.m_CellIdIsSet = true;
    } 
    if(j.contains("hoStatus"))
    {
        j.at("hoStatus").get_to(o.m_HoStatus);
        o.m_HoStatusIsSet = true;
    } 
}

std::string FilterCriteriaAssocHo::getAppInsId() const
{
    return m_AppInsId;
}
void FilterCriteriaAssocHo::setAppInsId(std::string const& value)
{
    m_AppInsId = value;
    m_AppInsIdIsSet = true;
}
bool FilterCriteriaAssocHo::appInsIdIsSet() const
{
    return m_AppInsIdIsSet;
}
void FilterCriteriaAssocHo::unsetAppInsId()
{
    m_AppInsIdIsSet = false;
}
AssociateId FilterCriteriaAssocHo::getAssociateId() const
{
    return m_AssociateId;
}
void FilterCriteriaAssocHo::setAssociateId(AssociateId const& value)
{
    m_AssociateId = value;
    m_AssociateIdIsSet = true;
}
bool FilterCriteriaAssocHo::associateIdIsSet() const
{
    return m_AssociateIdIsSet;
}
void FilterCriteriaAssocHo::unsetAssociateId()
{
    m_AssociateIdIsSet = false;
}
Plmn FilterCriteriaAssocHo::getPlmn() const
{
    return m_Plmn;
}
void FilterCriteriaAssocHo::setPlmn(Plmn const& value)
{
    m_Plmn = value;
    m_PlmnIsSet = true;
}
bool FilterCriteriaAssocHo::plmnIsSet() const
{
    return m_PlmnIsSet;
}
void FilterCriteriaAssocHo::unsetPlmn()
{
    m_PlmnIsSet = false;
}
std::vector<std::string>& FilterCriteriaAssocHo::getCellId()
{
    return m_CellId;
}
bool FilterCriteriaAssocHo::cellIdIsSet() const
{
    return m_CellIdIsSet;
}
void FilterCriteriaAssocHo::unsetCellId()
{
    m_CellIdIsSet = false;
}
HoStatus FilterCriteriaAssocHo::getHoStatus() const
{
    return m_HoStatus;
}
void FilterCriteriaAssocHo::setHoStatus(HoStatus const& value)
{
    m_HoStatus = value;
    m_HoStatusIsSet = true;
}
bool FilterCriteriaAssocHo::hoStatusIsSet() const
{
    return m_HoStatusIsSet;
}
void FilterCriteriaAssocHo::unsetHoStatus()
{
    m_HoStatusIsSet = false;
}

}
}
}

