/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_429.h
 *
 * 
 */

#ifndef Inline_response_429_H_
#define Inline_response_429_H_


#include "ProblemDetails.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_429
{
public:
    Inline_response_429();
    virtual ~Inline_response_429();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_429 members

    /// <summary>
    /// 
    /// </summary>
    ProblemDetails getProblemDetails() const;
    void setProblemDetails(ProblemDetails const& value);
    bool problemDetailsIsSet() const;
    void unsetProblemDetails();

    friend void to_json(nlohmann::json& j, const Inline_response_429& o);
    friend void from_json(const nlohmann::json& j, Inline_response_429& o);
protected:
    ProblemDetails m_ProblemDetails;
    bool m_ProblemDetailsIsSet;
};

}
}
}

#endif /* Inline_response_429_H_ */
