/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "MeasTaSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

MeasTaSubscription::MeasTaSubscription()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

MeasTaSubscription::~MeasTaSubscription()
{
}

void MeasTaSubscription::validate()
{
    // TODO: implement validation
}

nlohmann::json MeasTaSubscription::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["_links"] = ModelBase::toJson(m__links);
    val["filterCriteria"] = ModelBase::toJson(m_FilterCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void MeasTaSubscription::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string MeasTaSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void MeasTaSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link MeasTaSubscription::getLinks() const
{
    return m__links;
}
void MeasTaSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
FilterCriteriaAssoc MeasTaSubscription::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void MeasTaSubscription::setFilterCriteria(FilterCriteriaAssoc const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp MeasTaSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void MeasTaSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool MeasTaSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void MeasTaSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}
}

