/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Mp1SubscriptionLinkList_Links.h
 *
 * Self-referring URI.
 */

#ifndef Mp1SubscriptionLinkList_Links_H_
#define Mp1SubscriptionLinkList_Links_H_


#include "Mp1SubscriptionLinkList_Subscription.h"
#include "LinkType.h"
#include <vector>
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// Self-referring URI.
/// </summary>
class  Mp1SubscriptionLinkList_Links
{
public:
    Mp1SubscriptionLinkList_Links();
    virtual ~Mp1SubscriptionLinkList_Links();

    void validate();

    /////////////////////////////////////////////
    /// Mp1SubscriptionLinkList_Links members

    /// <summary>
    /// 
    /// </summary>
    LinkType getSelf() const;
    void setSelf(LinkType const& value);
        /// <summary>
    /// Subscription list
    /// </summary>
    std::vector<Mp1SubscriptionLinkList_Subscription>& getSubscription();
    bool subscriptionIsSet() const;
    void unsetSubscription();

    friend void to_json(nlohmann::json& j, const Mp1SubscriptionLinkList_Links& o);
    friend void from_json(const nlohmann::json& j, Mp1SubscriptionLinkList_Links& o);
protected:
    LinkType m_Self;

    std::vector<Mp1SubscriptionLinkList_Subscription> m_Subscription;
    bool m_SubscriptionIsSet;
};

}
}
}

#endif /* Mp1SubscriptionLinkList_Links_H_ */
