/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Mp1SubscriptionLinkList_Subscription.h
 *
 * A link to a subscription.
 */

#ifndef Mp1SubscriptionLinkList_Subscription_H_
#define Mp1SubscriptionLinkList_Subscription_H_

#include <string>
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// A link to a subscription.
/// </summary>
class  Mp1SubscriptionLinkList_Subscription
{
public:
    Mp1SubscriptionLinkList_Subscription();
    virtual ~Mp1SubscriptionLinkList_Subscription();

    void validate();

    /////////////////////////////////////////////
    /// Mp1SubscriptionLinkList_Subscription members

    /// <summary>
    /// URI referring to a resource
    /// </summary>
    std::string getHref() const;
    void setHref(std::string const& value);
        /// <summary>
    /// The values are as defined in the \&quot;subscriptionType\&quot; attribute for each different Mp1 event subscription data type.
    /// </summary>
    std::string getRel() const;
    void setRel(std::string const& value);
    
    friend void to_json(nlohmann::json& j, const Mp1SubscriptionLinkList_Subscription& o);
    friend void from_json(const nlohmann::json& j, Mp1SubscriptionLinkList_Subscription& o);
protected:
    std::string m_Href;

    std::string m_Rel;

};

}
}
}

#endif /* Mp1SubscriptionLinkList_Subscription_H_ */
