/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Mp1TrafficImsi.h"

namespace llmec {
namespace mp1 {
namespace model {

Mp1TrafficImsi::Mp1TrafficImsi()
{
    m_Service_ip = "";
    m_Port = 0;
    m_Transport = 0;
    m_Mec_ipaddr = "";
    m_Mec_macaddr = "";
    m_Type = 0;
    
}

Mp1TrafficImsi::~Mp1TrafficImsi()
{
}

void Mp1TrafficImsi::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Mp1TrafficImsi& o)
{
    j = nlohmann::json();
    j["ue_list"] = o.m_Ue_list;
    j["service_ip"] = o.m_Service_ip;
    j["port"] = o.m_Port;
    j["transport"] = o.m_Transport;
    j["mec_ipaddr"] = o.m_Mec_ipaddr;
    j["mec_macaddr"] = o.m_Mec_macaddr;
    j["type"] = o.m_Type;
}

void from_json(const nlohmann::json& j, Mp1TrafficImsi& o)
{
    j.at("ue_list").get_to(o.m_Ue_list);
    j.at("service_ip").get_to(o.m_Service_ip);
    j.at("port").get_to(o.m_Port);
    j.at("transport").get_to(o.m_Transport);
    j.at("mec_ipaddr").get_to(o.m_Mec_ipaddr);
    j.at("mec_macaddr").get_to(o.m_Mec_macaddr);
    j.at("type").get_to(o.m_Type);
}

std::vector<std::string>& Mp1TrafficImsi::getUeList()
{
    return m_Ue_list;
}
std::string Mp1TrafficImsi::getServiceIp() const
{
    return m_Service_ip;
}
void Mp1TrafficImsi::setServiceIp(std::string const& value)
{
    m_Service_ip = value;
    
}
int32_t Mp1TrafficImsi::getPort() const
{
    return m_Port;
}
void Mp1TrafficImsi::setPort(int32_t const value)
{
    m_Port = value;
    
}
int32_t Mp1TrafficImsi::getTransport() const
{
    return m_Transport;
}
void Mp1TrafficImsi::setTransport(int32_t const value)
{
    m_Transport = value;
    
}
std::string Mp1TrafficImsi::getMecIpaddr() const
{
    return m_Mec_ipaddr;
}
void Mp1TrafficImsi::setMecIpaddr(std::string const& value)
{
    m_Mec_ipaddr = value;
    
}
std::string Mp1TrafficImsi::getMecMacaddr() const
{
    return m_Mec_macaddr;
}
void Mp1TrafficImsi::setMecMacaddr(std::string const& value)
{
    m_Mec_macaddr = value;
    
}
int32_t Mp1TrafficImsi::getType() const
{
    return m_Type;
}
void Mp1TrafficImsi::setType(int32_t const value)
{
    m_Type = value;
    
}

}
}
}

