/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NotificationSubscription.h
 *
 * This type represents the information that the mobile edge platform notifies the subscribed application instance about  the corresponding application instance termination/stop.
 */

#ifndef NotificationSubscription_H_
#define NotificationSubscription_H_


#include "Self.h"
#include <string>
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// This type represents the information that the mobile edge platform notifies the subscribed application instance about  the corresponding application instance termination/stop.
/// </summary>
class  NotificationSubscription
{
public:
    NotificationSubscription();
    virtual ~NotificationSubscription();

    void validate();

    /////////////////////////////////////////////
    /// AppTerminationNotificationSubscription members

    /// <summary>
    /// Shall be set to AppTerminationNotificationSubscription.
    /// </summary>
    std::string getSubscriptionType() const;
    void setSubscriptionType(std::string const& value);
        /// <summary>
    /// URI selected by the mobile edge application instance to receive notifications on the subscribed mobile edge application instance management information. This shall be included in both the request and the response.
    /// </summary>
    std::string getCallbackReference() const;
    void setCallbackReference(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    Self getLinks() const;
    void setLinks(Self const& value);

    
    friend void to_json(nlohmann::json& j, const NotificationSubscription& o);
    friend void from_json(const nlohmann::json& j, NotificationSubscription& o);
protected:
    std::string m_SubscriptionType;

    std::string m_CallbackReference;

    Self m__links;


};

}
}
}

#endif /* AppTerminationNotificationSubscription_H_ */
