/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NotificationSubscription.h"

namespace llmec {
namespace mp1 {
namespace model {

NotificationSubscription::NotificationSubscription()
{
    m_SubscriptionType = "";
    m_CallbackReference = "";
    
}

NotificationSubscription::~NotificationSubscription()
{
}

void NotificationSubscription::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const NotificationSubscription& o)
{
    j = nlohmann::json();
    j["subscriptionType"] = o.m_SubscriptionType;
    j["callbackReference"] = o.m_CallbackReference;
    j["_links"] = o.m__links;

}

void from_json(const nlohmann::json& j, NotificationSubscription& o)
{
    j.at("subscriptionType").get_to(o.m_SubscriptionType);
    j.at("callbackReference").get_to(o.m_CallbackReference);
    j.at("_links").get_to(o.m__links);

}

std::string NotificationSubscription::getSubscriptionType() const
{
    return m_SubscriptionType;
}
void NotificationSubscription::setSubscriptionType(std::string const& value)
{
    m_SubscriptionType = value;
    
}
std::string NotificationSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void NotificationSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Self NotificationSubscription::getLinks() const
{
    return m__links;
}
void NotificationSubscription::setLinks(Self const& value)
{
    m__links = value;
    
}

}
}
}

