/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Plmn.h"

namespace llmec {
namespace mp1 {
namespace model {

Plmn::Plmn()
{
    m_Mcc = "";
    m_Mnc = "";
    
}

Plmn::~Plmn()
{
}

void Plmn::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Plmn& o)
{
    j = nlohmann::json();
    j["mcc"] = o.m_Mcc;
    j["mnc"] = o.m_Mnc;
}

void from_json(const nlohmann::json& j, Plmn& o)
{
    j.at("mcc").get_to(o.m_Mcc);
    j.at("mnc").get_to(o.m_Mnc);
}

std::string Plmn::getMcc() const
{
    return m_Mcc;
}
void Plmn::setMcc(std::string const& value)
{
    m_Mcc = value;
    
}
std::string Plmn::getMnc() const
{
    return m_Mnc;
}
void Plmn::setMnc(std::string const& value)
{
    m_Mnc = value;
    
}

}
}
}

