/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PlmnInfo.h
 *
 * 
 */

#ifndef PlmnInfo_H_
#define PlmnInfo_H_


#include "Ecgi.h"
#include <string>
#include "TimeStamp.h"
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  PlmnInfo
{
public:
    PlmnInfo();
    virtual ~PlmnInfo();

    void validate();

    /////////////////////////////////////////////
    /// PlmnInfo members

    /// <summary>
    /// 
    /// </summary>
    TimeStamp getTimeStamp() const;
    void setTimeStamp(TimeStamp const& value);
    bool timeStampIsSet() const;
    void unsetTimeStamp();
    /// <summary>
    /// Unique identifier for the mobile edge application instance
    /// </summary>
    std::string getAppInsId() const;
    void setAppInsId(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    Ecgi getEcgi() const;
    void setEcgi(Ecgi const& value);
    
    friend void to_json(nlohmann::json& j, const PlmnInfo& o);
    friend void from_json(const nlohmann::json& j, PlmnInfo& o);
protected:
    TimeStamp m_TimeStamp;
    bool m_TimeStampIsSet;
    std::string m_AppInsId;

    Ecgi m_Ecgi;

};

}
}
}

#endif /* PlmnInfo_H_ */
