/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnInfo.h"

namespace llmec {
namespace mp1 {
namespace model {

PlmnInfo::PlmnInfo()
{
    m_TimeStampIsSet = false;
    m_AppInsId = "";
    
}

PlmnInfo::~PlmnInfo()
{
}

void PlmnInfo::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const PlmnInfo& o)
{
    j = nlohmann::json();
    if(o.timeStampIsSet())
        j["timeStamp"] = o.m_TimeStamp;
    j["appInsId"] = o.m_AppInsId;
    j["ecgi"] = o.m_Ecgi;
}

void from_json(const nlohmann::json& j, PlmnInfo& o)
{
    if(j.contains("timeStamp"))
    {
        j.at("timeStamp").get_to(o.m_TimeStamp);
        o.m_TimeStampIsSet = true;
    } 
    j.at("appInsId").get_to(o.m_AppInsId);
    j.at("ecgi").get_to(o.m_Ecgi);
}

TimeStamp PlmnInfo::getTimeStamp() const
{
    return m_TimeStamp;
}
void PlmnInfo::setTimeStamp(TimeStamp const& value)
{
    m_TimeStamp = value;
    m_TimeStampIsSet = true;
}
bool PlmnInfo::timeStampIsSet() const
{
    return m_TimeStampIsSet;
}
void PlmnInfo::unsetTimeStamp()
{
    m_TimeStampIsSet = false;
}
std::string PlmnInfo::getAppInsId() const
{
    return m_AppInsId;
}
void PlmnInfo::setAppInsId(std::string const& value)
{
    m_AppInsId = value;
    
}
Ecgi PlmnInfo::getEcgi() const
{
    return m_Ecgi;
}
void PlmnInfo::setEcgi(Ecgi const& value)
{
    m_Ecgi = value;
    
}

}
}
}

