/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "QosInformation.h"

namespace llmec {
namespace mp1 {
namespace model {

QosInformation::QosInformation()
{
    m_ErabMbrDl = 0;
    m_ErabMbrUl = 0;
    m_ErabGbrDl = 0;
    m_ErabGbrUl = 0;
    
}

QosInformation::~QosInformation()
{
}

void QosInformation::validate()
{
    // TODO: implement validation
}

nlohmann::json QosInformation::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["erabMbrDl"] = m_ErabMbrDl;
    val["erabMbrUl"] = m_ErabMbrUl;
    val["erabGbrDl"] = m_ErabGbrDl;
    val["erabGbrUl"] = m_ErabGbrUl;
    

    return val;
}

void QosInformation::fromJson(const nlohmann::json& val)
{
    setErabMbrDl(val.at("erabMbrDl"));
    setErabMbrUl(val.at("erabMbrUl"));
    setErabGbrDl(val.at("erabGbrDl"));
    setErabGbrUl(val.at("erabGbrUl"));
    
}


int32_t QosInformation::getErabMbrDl() const
{
    return m_ErabMbrDl;
}
void QosInformation::setErabMbrDl(int32_t const value)
{
    m_ErabMbrDl = value;
    
}
int32_t QosInformation::getErabMbrUl() const
{
    return m_ErabMbrUl;
}
void QosInformation::setErabMbrUl(int32_t const value)
{
    m_ErabMbrUl = value;
    
}
int32_t QosInformation::getErabGbrDl() const
{
    return m_ErabGbrDl;
}
void QosInformation::setErabGbrDl(int32_t const value)
{
    m_ErabGbrDl = value;
    
}
int32_t QosInformation::getErabGbrUl() const
{
    return m_ErabGbrUl;
}
void QosInformation::setErabGbrUl(int32_t const value)
{
    m_ErabGbrUl = value;
    
}

}
}
}

