/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "QosInformation.h"

namespace llmec {
namespace mp1 {
namespace model {

QosInformation::QosInformation()
{
    m_ErabMbrDl = 0;
    m_ErabMbrUl = 0;
    m_ErabGbrDl = 0;
    m_ErabGbrUl = 0;
    
}

QosInformation::~QosInformation()
{
}

void QosInformation::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const QosInformation& o)
{
    j = nlohmann::json();
    j["erabMbrDl"] = o.m_ErabMbrDl;
    j["erabMbrUl"] = o.m_ErabMbrUl;
    j["erabGbrDl"] = o.m_ErabGbrDl;
    j["erabGbrUl"] = o.m_ErabGbrUl;
}

void from_json(const nlohmann::json& j, QosInformation& o)
{
    j.at("erabMbrDl").get_to(o.m_ErabMbrDl);
    j.at("erabMbrUl").get_to(o.m_ErabMbrUl);
    j.at("erabGbrDl").get_to(o.m_ErabGbrDl);
    j.at("erabGbrUl").get_to(o.m_ErabGbrUl);
}

int32_t QosInformation::getErabMbrDl() const
{
    return m_ErabMbrDl;
}
void QosInformation::setErabMbrDl(int32_t const value)
{
    m_ErabMbrDl = value;
    
}
int32_t QosInformation::getErabMbrUl() const
{
    return m_ErabMbrUl;
}
void QosInformation::setErabMbrUl(int32_t const value)
{
    m_ErabMbrUl = value;
    
}
int32_t QosInformation::getErabGbrDl() const
{
    return m_ErabGbrDl;
}
void QosInformation::setErabGbrDl(int32_t const value)
{
    m_ErabGbrDl = value;
    
}
int32_t QosInformation::getErabGbrUl() const
{
    return m_ErabGbrUl;
}
void QosInformation::setErabGbrUl(int32_t const value)
{
    m_ErabGbrUl = value;
    
}

}
}
}

