/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RabInfo.h
 *
 * 
 */

#ifndef RabInfo_H_
#define RabInfo_H_


#include "CellUserInfo.h"
#include <string>
#include <vector>
#include "TimeStamp.h"
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  RabInfo
{
public:
    RabInfo();
    virtual ~RabInfo();

    void validate();

    /////////////////////////////////////////////
    /// RabInfo members

    /// <summary>
    /// 
    /// </summary>
    TimeStamp getTimeStamp() const;
    void setTimeStamp(TimeStamp const& value);
    bool timeStampIsSet() const;
    void unsetTimeStamp();
    /// <summary>
    /// Unique identifier for the mobile edge application instance
    /// </summary>
    std::string getAppInsId() const;
    void setAppInsId(std::string const& value);
        /// <summary>
    /// Unique identifier allocated by the Mobile Edge application for the Information request.
    /// </summary>
    std::string getRequestId() const;
    void setRequestId(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<CellUserInfo>& getCellUserInfo();
    bool cellUserInfoIsSet() const;
    void unsetCellUserInfo();

    friend void to_json(nlohmann::json& j, const RabInfo& o);
    friend void from_json(const nlohmann::json& j, RabInfo& o);
protected:
    TimeStamp m_TimeStamp;
    bool m_TimeStampIsSet;
    std::string m_AppInsId;

    std::string m_RequestId;

    std::vector<CellUserInfo> m_CellUserInfo;
    bool m_CellUserInfoIsSet;
};

}
}
}

#endif /* RabInfo_H_ */
