/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RabRelSubscriptionPost.h
 *
 * 
 */

#ifndef RabRelSubscriptionPost_H_
#define RabRelSubscriptionPost_H_


#include <string>
#include "FilterCriteriaAssocQci.h"
#include "TimeStamp.h"
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  RabRelSubscriptionPost
{
public:
    RabRelSubscriptionPost();
    virtual ~RabRelSubscriptionPost();

    void validate();

    /////////////////////////////////////////////
    /// RabRelSubscriptionPost members

    /// <summary>
    /// URL selected by the Mobile Edge application to receive notifications on the subscribed RNIS information.
    /// </summary>
    std::string getCallbackReference() const;
    void setCallbackReference(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    FilterCriteriaAssocQci getFilterCriteria() const;
    void setFilterCriteria(FilterCriteriaAssocQci const& value);
        /// <summary>
    /// 
    /// </summary>
    TimeStamp getExpiryDeadline() const;
    void setExpiryDeadline(TimeStamp const& value);
    bool expiryDeadlineIsSet() const;
    void unsetExpiryDeadline();

    friend void to_json(nlohmann::json& j, const RabRelSubscriptionPost& o);
    friend void from_json(const nlohmann::json& j, RabRelSubscriptionPost& o);
protected:
    std::string m_CallbackReference;

    FilterCriteriaAssocQci m_FilterCriteria;

    TimeStamp m_ExpiryDeadline;
    bool m_ExpiryDeadlineIsSet;
};

}
}
}

#endif /* RabRelSubscriptionPost_H_ */
