/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RabRelSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RabRelSubscription::RabRelSubscription()
{
    m_CallbackReference = "";
    m_ExpiryDeadlineIsSet = false;
    
}

RabRelSubscription::~RabRelSubscription()
{
}

void RabRelSubscription::validate()
{
    // TODO: implement validation
}

nlohmann::json RabRelSubscription::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["_links"] = ModelBase::toJson(m__links);
    val["filterCriteria"] = ModelBase::toJson(m_FilterCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void RabRelSubscription::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string RabRelSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void RabRelSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link RabRelSubscription::getLinks() const
{
    return m__links;
}
void RabRelSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
FilterCriteriaAssocQci RabRelSubscription::getFilterCriteria() const
{
    return m_FilterCriteria;
}
void RabRelSubscription::setFilterCriteria(FilterCriteriaAssocQci const& value)
{
    m_FilterCriteria = value;
    
}
TimeStamp RabRelSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void RabRelSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool RabRelSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void RabRelSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}
}

