/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * S1BearerInfo.h
 *
 * 
 */

#ifndef S1BearerInfo_H_
#define S1BearerInfo_H_


#include "S1UeInfo.h"
#include <vector>
#include "TimeStamp.h"
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  S1BearerInfo
{
public:
    S1BearerInfo();
    virtual ~S1BearerInfo();

    void validate();

    /////////////////////////////////////////////
    /// S1BearerInfo members

    /// <summary>
    /// 
    /// </summary>
    TimeStamp getTimeStamp() const;
    void setTimeStamp(TimeStamp const& value);
    bool timeStampIsSet() const;
    void unsetTimeStamp();
    /// <summary>
    /// 
    /// </summary>
    std::vector<S1UeInfo>& getS1UeInfo();
    
    friend void to_json(nlohmann::json& j, const S1BearerInfo& o);
    friend void from_json(const nlohmann::json& j, S1BearerInfo& o);
protected:
    TimeStamp m_TimeStamp;
    bool m_TimeStampIsSet;
    std::vector<S1UeInfo> m_S1UeInfo;

};

}
}
}

#endif /* S1BearerInfo_H_ */
