/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "S1BearerSubscription.h"

namespace llmec {
namespace mp1 {
namespace model {

S1BearerSubscription::S1BearerSubscription()
{
    m_CallbackReference = "";
    m_EventTypeIsSet = false;
    m_ExpiryDeadlineIsSet = false;
    
}

S1BearerSubscription::~S1BearerSubscription()
{
}

void S1BearerSubscription::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const S1BearerSubscription& o)
{
    j = nlohmann::json();
    j["callbackReference"] = o.m_CallbackReference;
    j["_links"] = o.m__links;
    if(o.eventTypeIsSet())
        j["eventType"] = o.m_EventType;
    j["s1BearerSubscriptionCriteria"] = o.m_S1BearerSubscriptionCriteria;
    if(o.expiryDeadlineIsSet())
        j["expiryDeadline"] = o.m_ExpiryDeadline;
}

void from_json(const nlohmann::json& j, S1BearerSubscription& o)
{
    j.at("callbackReference").get_to(o.m_CallbackReference);
    j.at("_links").get_to(o.m__links);
    if(j.contains("eventType"))
    {
        j.at("eventType").get_to(o.m_EventType);
        o.m_EventTypeIsSet = true;
    } 
    j.at("s1BearerSubscriptionCriteria").get_to(o.m_S1BearerSubscriptionCriteria);
    if(j.contains("expiryDeadline"))
    {
        j.at("expiryDeadline").get_to(o.m_ExpiryDeadline);
        o.m_ExpiryDeadlineIsSet = true;
    } 
}

std::string S1BearerSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void S1BearerSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link S1BearerSubscription::getLinks() const
{
    return m__links;
}
void S1BearerSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
EventType S1BearerSubscription::getEventType() const
{
    return m_EventType;
}
void S1BearerSubscription::setEventType(EventType const& value)
{
    m_EventType = value;
    m_EventTypeIsSet = true;
}
bool S1BearerSubscription::eventTypeIsSet() const
{
    return m_EventTypeIsSet;
}
void S1BearerSubscription::unsetEventType()
{
    m_EventTypeIsSet = false;
}
S1BearerSubscriptionCriteria S1BearerSubscription::getS1BearerSubscriptionCriteria() const
{
    return m_S1BearerSubscriptionCriteria;
}
void S1BearerSubscription::setS1BearerSubscriptionCriteria(S1BearerSubscriptionCriteria const& value)
{
    m_S1BearerSubscriptionCriteria = value;
    
}
TimeStamp S1BearerSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void S1BearerSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool S1BearerSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void S1BearerSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}

