/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * S1BearerSubscription.h
 *
 * 
 */

#ifndef S1BearerSubscription_H_
#define S1BearerSubscription_H_


#include "S1BearerSubscriptionCriteria.h"
#include <string>
#include "EventType.h"
#include "Link.h"
#include "TimeStamp.h"
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  S1BearerSubscription
{
public:
    S1BearerSubscription();
    virtual ~S1BearerSubscription();

    void validate();

    /////////////////////////////////////////////
    /// S1BearerSubscription members

    /// <summary>
    /// URL selected by the Mobile Edge application to receive notifications on the subscribed RNIS information.
    /// </summary>
    std::string getCallbackReference() const;
    void setCallbackReference(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    Link getLinks() const;
    void setLinks(Link const& value);
        /// <summary>
    /// 
    /// </summary>
    EventType getEventType() const;
    void setEventType(EventType const& value);
    bool eventTypeIsSet() const;
    void unsetEventType();
    /// <summary>
    /// 
    /// </summary>
    S1BearerSubscriptionCriteria getS1BearerSubscriptionCriteria() const;
    void setS1BearerSubscriptionCriteria(S1BearerSubscriptionCriteria const& value);
        /// <summary>
    /// 
    /// </summary>
    TimeStamp getExpiryDeadline() const;
    void setExpiryDeadline(TimeStamp const& value);
    bool expiryDeadlineIsSet() const;
    void unsetExpiryDeadline();

    friend void to_json(nlohmann::json& j, const S1BearerSubscription& o);
    friend void from_json(const nlohmann::json& j, S1BearerSubscription& o);
protected:
    std::string m_CallbackReference;

    Link m__links;

    EventType m_EventType;
    bool m_EventTypeIsSet;
    S1BearerSubscriptionCriteria m_S1BearerSubscriptionCriteria;

    TimeStamp m_ExpiryDeadline;
    bool m_ExpiryDeadlineIsSet;
};

}
}
}

#endif /* S1BearerSubscription_H_ */
