/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "S1BearerSubscription.h"

namespace llmec {
namespace mp1 {
namespace model {

S1BearerSubscription::S1BearerSubscription()
{
    m_CallbackReference = "";
    m_EventTypeIsSet = false;
    m_ExpiryDeadlineIsSet = false;
    
}

S1BearerSubscription::~S1BearerSubscription()
{
}

void S1BearerSubscription::validate()
{
    // TODO: implement validation
}

nlohmann::json S1BearerSubscription::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["callbackReference"] = ModelBase::toJson(m_CallbackReference);
    val["_links"] = ModelBase::toJson(m__links);
    if(m_EventTypeIsSet)
    {
        val["eventType"] = ModelBase::toJson(m_EventType);
    }
    val["s1BearerSubscriptionCriteria"] = ModelBase::toJson(m_S1BearerSubscriptionCriteria);
    if(m_ExpiryDeadlineIsSet)
    {
        val["expiryDeadline"] = ModelBase::toJson(m_ExpiryDeadline);
    }
    

    return val;
}

void S1BearerSubscription::fromJson(const nlohmann::json& val)
{
    setCallbackReference(val.at("callbackReference"));
    if(val.find("eventType") != val.end())
    {
        if(!val["eventType"].is_null())
        {
            EventType newItem;
            newItem.fromJson(val["eventType"]);
            setEventType( newItem );
        }
        
    }
    if(val.find("expiryDeadline") != val.end())
    {
        if(!val["expiryDeadline"].is_null())
        {
            TimeStamp newItem;
            newItem.fromJson(val["expiryDeadline"]);
            setExpiryDeadline( newItem );
        }
        
    }
    
}


std::string S1BearerSubscription::getCallbackReference() const
{
    return m_CallbackReference;
}
void S1BearerSubscription::setCallbackReference(std::string const& value)
{
    m_CallbackReference = value;
    
}
Link S1BearerSubscription::getLinks() const
{
    return m__links;
}
void S1BearerSubscription::setLinks(Link const& value)
{
    m__links = value;
    
}
EventType S1BearerSubscription::getEventType() const
{
    return m_EventType;
}
void S1BearerSubscription::setEventType(EventType const& value)
{
    m_EventType = value;
    m_EventTypeIsSet = true;
}
bool S1BearerSubscription::eventTypeIsSet() const
{
    return m_EventTypeIsSet;
}
void S1BearerSubscription::unsetEventType()
{
    m_EventTypeIsSet = false;
}
S1BearerSubscriptionCriteria S1BearerSubscription::getS1BearerSubscriptionCriteria() const
{
    return m_S1BearerSubscriptionCriteria;
}
void S1BearerSubscription::setS1BearerSubscriptionCriteria(S1BearerSubscriptionCriteria const& value)
{
    m_S1BearerSubscriptionCriteria = value;
    
}
TimeStamp S1BearerSubscription::getExpiryDeadline() const
{
    return m_ExpiryDeadline;
}
void S1BearerSubscription::setExpiryDeadline(TimeStamp const& value)
{
    m_ExpiryDeadline = value;
    m_ExpiryDeadlineIsSet = true;
}
bool S1BearerSubscription::expiryDeadlineIsSet() const
{
    return m_ExpiryDeadlineIsSet;
}
void S1BearerSubscription::unsetExpiryDeadline()
{
    m_ExpiryDeadlineIsSet = false;
}

}
}
}

