/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "S1EnbInfo.h"

namespace llmec {
namespace mp1 {
namespace model {

S1EnbInfo::S1EnbInfo()
{
    m_IpAddress = "";
    m_TunnelId = "";
    
}

S1EnbInfo::~S1EnbInfo()
{
}

void S1EnbInfo::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const S1EnbInfo& o)
{
    j = nlohmann::json();
    j["ipAddress"] = o.m_IpAddress;
    j["tunnelId"] = o.m_TunnelId;
}

void from_json(const nlohmann::json& j, S1EnbInfo& o)
{
    j.at("ipAddress").get_to(o.m_IpAddress);
    j.at("tunnelId").get_to(o.m_TunnelId);
}

std::string S1EnbInfo::getIpAddress() const
{
    return m_IpAddress;
}
void S1EnbInfo::setIpAddress(std::string const& value)
{
    m_IpAddress = value;
    
}
std::string S1EnbInfo::getTunnelId() const
{
    return m_TunnelId;
}
void S1EnbInfo::setTunnelId(std::string const& value)
{
    m_TunnelId = value;
    
}

}
}
}

