/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * S1UeInfo.h
 *
 * The information on users per cell.
 */

#ifndef S1UeInfo_H_
#define S1UeInfo_H_


#include "ModelBase.h"

#include "Ecgi.h"
#include "TempUeId.h"
#include "S1BearerInfoDetailed.h"
#include "AssociateId.h"
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// The information on users per cell.
/// </summary>
class  S1UeInfo
    : public ModelBase
{
public:
    S1UeInfo();
    virtual ~S1UeInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// S1UeInfo members

    /// <summary>
    /// 
    /// </summary>
    std::vector<TempUeId>& getTempUeId();
        /// <summary>
    /// 
    /// </summary>
    std::vector<AssociateId>& getAssociateId();
    bool associateIdIsSet() const;
    void unsetAssociateId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Ecgi>& getEcgi();
        /// <summary>
    /// 
    /// </summary>
    std::vector<S1BearerInfoDetailed>& getS1BearerInfoDetailed();
    
protected:
    std::vector<TempUeId> m_TempUeId;

    std::vector<AssociateId> m_AssociateId;
    bool m_AssociateIdIsSet;
    std::vector<Ecgi> m_Ecgi;

    std::vector<S1BearerInfoDetailed> m_S1BearerInfoDetailed;

};

}
}
}
}

#endif /* S1UeInfo_H_ */
