/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SecurityInfo_OAuth2Info.h"

namespace llmec {
namespace mp1 {
namespace model {

SecurityInfo_OAuth2Info::SecurityInfo_OAuth2Info()
{
    m_TokenEndpoint = "";
    
}

SecurityInfo_OAuth2Info::~SecurityInfo_OAuth2Info()
{
}

void SecurityInfo_OAuth2Info::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const SecurityInfo_OAuth2Info& o)
{
    j = nlohmann::json();
    j["grantTypes"] = o.m_GrantTypes;
    j["tokenEndpoint"] = o.m_TokenEndpoint;
}

void from_json(const nlohmann::json& j, SecurityInfo_OAuth2Info& o)
{
    j.at("grantTypes").get_to(o.m_GrantTypes);
    j.at("tokenEndpoint").get_to(o.m_TokenEndpoint);
}

std::vector<std::string>& SecurityInfo_OAuth2Info::getGrantTypes()
{
    return m_GrantTypes;
}
std::string SecurityInfo_OAuth2Info::getTokenEndpoint() const
{
    return m_TokenEndpoint;
}
void SecurityInfo_OAuth2Info::setTokenEndpoint(std::string const& value)
{
    m_TokenEndpoint = value;
    
}

}
}
}

