/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SecurityInfo_OAuth2Info_GrantTypes.h
 *
 * List of supported OAuth 2.0 grant types
 */

#ifndef SecurityInfo_OAuth2Info_GrantTypes_H_
#define SecurityInfo_OAuth2Info_GrantTypes_H_


#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// List of supported OAuth 2.0 grant types
/// </summary>
class  SecurityInfo_OAuth2Info_GrantTypes
{
public:
    SecurityInfo_OAuth2Info_GrantTypes();
    virtual ~SecurityInfo_OAuth2Info_GrantTypes();

    void validate();

    /////////////////////////////////////////////
    /// SecurityInfo_OAuth2Info_GrantTypes members


    friend void to_json(nlohmann::json& j, const SecurityInfo_OAuth2Info_GrantTypes& o);
    friend void from_json(const nlohmann::json& j, SecurityInfo_OAuth2Info_GrantTypes& o);
protected:
};

}
}
}

#endif /* SecurityInfo_OAuth2Info_GrantTypes_H_ */
