/**
* Mp1 API
* The ETSI MEC ISG MEC011 Application Enablement API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* Contact: cti_support@etsi.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ServiceAvailabilityNotification.h"

namespace llmec {
namespace mp1 {
namespace model {

ServiceAvailabilityNotification::ServiceAvailabilityNotification()
{
    m_NotificationType = "";
    
}

ServiceAvailabilityNotification::~ServiceAvailabilityNotification()
{
}

void ServiceAvailabilityNotification::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const ServiceAvailabilityNotification& o)
{
    j = nlohmann::json();
    j["notificationType"] = o.m_NotificationType;
    j["services"] = o.m_Services;
    j["_links"] = o.m__links;
}

void from_json(const nlohmann::json& j, ServiceAvailabilityNotification& o)
{
    j.at("notificationType").get_to(o.m_NotificationType);
    j.at("services").get_to(o.m_Services);
    j.at("_links").get_to(o.m__links);
}

std::string ServiceAvailabilityNotification::getNotificationType() const
{
    return m_NotificationType;
}
void ServiceAvailabilityNotification::setNotificationType(std::string const& value)
{
    m_NotificationType = value;
    
}
std::vector<ServiceInfo>& ServiceAvailabilityNotification::getServices()
{
    return m_Services;
}
Subscription ServiceAvailabilityNotification::getLinks() const
{
    return m__links;
}
void ServiceAvailabilityNotification::setLinks(Subscription const& value)
{
    m__links = value;
    
}

}
}
}

