/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ServiceInfo_Post.h"

namespace llmec {
namespace mp1 {
namespace model {

ServiceInfo_Post::ServiceInfo_Post()
{
    
}

ServiceInfo_Post::~ServiceInfo_Post()
{
}

void ServiceInfo_Post::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const ServiceInfo_Post& o)
{
    j = nlohmann::json();
}

void from_json(const nlohmann::json& j, ServiceInfo_Post& o)
{
}


}
}
}

