/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI AND som additional MEC APIs
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionLinkList.h
 *
 * 
 */

#ifndef SubscriptionLinkList_H_
#define SubscriptionLinkList_H_


#include "ModelBase.h"

#include "Link.h"
#include <vector>
#include "Subscription.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscriptionLinkList
    : public ModelBase
{
public:
    SubscriptionLinkList();
    virtual ~SubscriptionLinkList();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// SubscriptionLinkList members

    /// <summary>
    /// 
    /// </summary>
    Link getLinks() const;
    void setLinks(Link const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Subscription>& getSubscription();
    bool subscriptionIsSet() const;
    void unsetSubscription();

protected:
    Link m__links;

    std::vector<Subscription> m_Subscription;
    bool m_SubscriptionIsSet;
};

}
}
}

#endif /* SubscriptionLinkList_H_ */
