/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionLinkList.h
 *
 * 
 */

#ifndef SubscriptionLinkList_H_
#define SubscriptionLinkList_H_


#include "Link.h"
#include <vector>
#include "Subscription.h"
#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscriptionLinkList
{
public:
    SubscriptionLinkList();
    virtual ~SubscriptionLinkList();

    void validate();

    /////////////////////////////////////////////
    /// SubscriptionLinkList members

    /// <summary>
    /// 
    /// </summary>
    Link getLinks() const;
    void setLinks(Link const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Subscription>& getSubscription();
    bool subscriptionIsSet() const;
    void unsetSubscription();

    friend void to_json(nlohmann::json& j, const SubscriptionLinkList& o);
    friend void from_json(const nlohmann::json& j, SubscriptionLinkList& o);
protected:
    Link m__links;

    std::vector<Subscription> m_Subscription;
    bool m_SubscriptionIsSet;
};

}
}
}

#endif /* SubscriptionLinkList_H_ */
