/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionType.h
 *
 * Numeric value corresponding to specified type of subscription.
 */

#ifndef SubscriptionType_H_
#define SubscriptionType_H_


#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// Numeric value corresponding to specified type of subscription.
/// </summary>
class  SubscriptionType
{
public:
    SubscriptionType();
    virtual ~SubscriptionType();

    void validate();

    /////////////////////////////////////////////
    /// SubscriptionType members


    friend void to_json(nlohmann::json& j, const SubscriptionType& o);
    friend void from_json(const nlohmann::json& j, SubscriptionType& o);
protected:
};

}
}
}

#endif /* SubscriptionType_H_ */
