/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Subscription.h"

namespace llmec {
namespace mp1 {
namespace model {

Subscription::Subscription()
{
    m_Href = "";
    
}

Subscription::~Subscription()
{
}

void Subscription::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Subscription& o)
{
    j = nlohmann::json();
    j["href"] = o.m_Href;
    j["subscriptionType"] = o.m_SubscriptionType;
}

void from_json(const nlohmann::json& j, Subscription& o)
{
    j.at("href").get_to(o.m_Href);
    j.at("subscriptionType").get_to(o.m_SubscriptionType);
}

std::string Subscription::getHref() const
{
    return m_Href;
}
void Subscription::setHref(std::string const& value)
{
    m_Href = value;
    
}
SubscriptionType Subscription::getSubscriptionType() const
{
    return m_SubscriptionType;
}
void Subscription::setSubscriptionType(SubscriptionType const& value)
{
    m_SubscriptionType = value;
    
}

}
}
}

