/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TempUeId.h
 *
 * 
 */

#ifndef TempUeId_H_
#define TempUeId_H_


#include <string>
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  TempUeId
{
public:
    TempUeId();
    virtual ~TempUeId();

    void validate();

    /////////////////////////////////////////////
    /// TempUeId members

    /// <summary>
    /// MMEC (MME Code) as defined in ETSI TS 136 413
    /// </summary>
    std::string getMmec() const;
    void setMmec(std::string const& value);
        /// <summary>
    /// M-TMSI (MME Mobile Subscriber Identity) as defined in ETSI TS 136 413
    /// </summary>
    std::string getMtmsi() const;
    void setMtmsi(std::string const& value);
    
    friend void to_json(nlohmann::json& j, const TempUeId& o);
    friend void from_json(const nlohmann::json& j, TempUeId& o);
protected:
    std::string m_Mmec;

    std::string m_Mtmsi;

};

}
}
}

#endif /* TempUeId_H_ */
