/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TempUeId.h"

namespace llmec {
namespace mp1 {
namespace model {

TempUeId::TempUeId()
{
    m_Mmec = "";
    m_Mtmsi = "";
    
}

TempUeId::~TempUeId()
{
}

void TempUeId::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const TempUeId& o)
{
    j = nlohmann::json();
    j["mmec"] = o.m_Mmec;
    j["mtmsi"] = o.m_Mtmsi;
}

void from_json(const nlohmann::json& j, TempUeId& o)
{
    j.at("mmec").get_to(o.m_Mmec);
    j.at("mtmsi").get_to(o.m_Mtmsi);
}

std::string TempUeId::getMmec() const
{
    return m_Mmec;
}
void TempUeId::setMmec(std::string const& value)
{
    m_Mmec = value;
    
}
std::string TempUeId::getMtmsi() const
{
    return m_Mtmsi;
}
void TempUeId::setMtmsi(std::string const& value)
{
    m_Mtmsi = value;
    
}

}
}
}

