/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TransportTypes.h
 *
 * The enumeration TransportTypes represents types of transports
 */

#ifndef TransportTypes_H_
#define TransportTypes_H_


#include "json.h"

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// The enumeration TransportTypes represents types of transports
/// </summary>
class  TransportTypes
{
public:
    TransportTypes();
    virtual ~TransportTypes();

    void validate();

    /////////////////////////////////////////////
    /// TransportTypes members


    friend void to_json(nlohmann::json& j, const TransportTypes& o);
    friend void from_json(const nlohmann::json& j, TransportTypes& o);
protected:
};

}
}
}

#endif /* TransportTypes_H_ */
