/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeInfo.h
 *
 * Information on UEs in the specific cell.
 */

#ifndef UeInfo_H_
#define UeInfo_H_


#include "ErabQosParameters.h"
#include "AssociateId.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace llmec {
namespace mp1 {
namespace model {

/// <summary>
/// Information on UEs in the specific cell.
/// </summary>
class  UeInfo
{
public:
    UeInfo();
    virtual ~UeInfo();

    void validate();

    /////////////////////////////////////////////
    /// UeInfo members

    /// <summary>
    /// 
    /// </summary>
    std::vector<AssociateId>& getAssociateId();
    bool associateIdIsSet() const;
    void unsetAssociateId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<ErabQosParameters>& getErabInfo();
    
    friend void to_json(nlohmann::json& j, const UeInfo& o);
    friend void from_json(const nlohmann::json& j, UeInfo& o);
protected:
    std::vector<AssociateId> m_AssociateId;
    bool m_AssociateIdIsSet;
    std::vector<ErabQosParameters> m_ErabInfo;

};

}
}
}

#endif /* UeInfo_H_ */
