/**
* MP1 API
* The ETSI MEC ISG MEC012 Radio Network Information API, AND The ETSI MEC ISG MEC011 Application Enablement API
* AND some additional MEC APIs described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UeInfo.h"

namespace llmec {
namespace mp1 {
namespace model {

UeInfo::UeInfo()
{
    m_AssociateIdIsSet = false;
    
}

UeInfo::~UeInfo()
{
}

void UeInfo::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const UeInfo& o)
{
    j = nlohmann::json();
    if(o.associateIdIsSet())
        j["associateId"] = o.m_AssociateId;
    j["erabInfo"] = o.m_ErabInfo;
}

void from_json(const nlohmann::json& j, UeInfo& o)
{
    if(j.contains("associateId"))
    {
        j.at("associateId").get_to(o.m_AssociateId);
        o.m_AssociateIdIsSet = true;
    } 
    j.at("erabInfo").get_to(o.m_ErabInfo);
}

std::vector<AssociateId>& UeInfo::getAssociateId()
{
    return m_AssociateId;
}
bool UeInfo::associateIdIsSet() const
{
    return m_AssociateIdIsSet;
}
void UeInfo::unsetAssociateId()
{
    m_AssociateIdIsSet = false;
}
std::vector<ErabQosParameters>& UeInfo::getErabInfo()
{
    return m_ErabInfo;
}

}
}
}

