/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ErabQosParametersQci.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ErabQosParameters_qci::ErabQosParameters_qci()
{
    m_QosInformationIsSet = false;
    
}

ErabQosParameters_qci::~ErabQosParameters_qci()
{
}

void ErabQosParameters_qci::validate()
{
    // TODO: implement validation
}

nlohmann::json ErabQosParameters_qci::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_QosInformationIsSet)
    {
        val["qosInformation"] = ModelBase::toJson(m_QosInformation);
    }
    

    return val;
}

void ErabQosParameters_qci::fromJson(const nlohmann::json& val)
{
    if(val.find("qosInformation") != val.end())
    {
        if(!val["qosInformation"].is_null())
        {
            QosInformation newItem;
            newItem.fromJson(val["qosInformation"]);
            setQosInformation( newItem );
        }
        
    }
    
}


QosInformation ErabQosParameters_qci::getQosInformation() const
{
    return m_QosInformation;
}
void ErabQosParameters_qci::setQosInformation(QosInformation const& value)
{
    m_QosInformation = value;
    m_QosInformationIsSet = true;
}
bool ErabQosParameters_qci::qosInformationIsSet() const
{
    return m_QosInformationIsSet;
}
void ErabQosParameters_qci::unsetQosInformation()
{
    m_QosInformationIsSet = false;
}

}
}
}
}

