/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "FilterCriteriaAssocTri.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

FilterCriteriaAssocTri::FilterCriteriaAssocTri()
{
    m_AppInsId = "";
    m_AppInsIdIsSet = false;
    m_AssociateIdIsSet = false;
    m_PlmnIsSet = false;
    m_CellIdIsSet = false;
    m_TriggerIsSet = false;
    
}

FilterCriteriaAssocTri::~FilterCriteriaAssocTri()
{
}

void FilterCriteriaAssocTri::validate()
{
    // TODO: implement validation
}

nlohmann::json FilterCriteriaAssocTri::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_AppInsIdIsSet)
    {
        val["appInsId"] = ModelBase::toJson(m_AppInsId);
    }
    if(m_AssociateIdIsSet)
    {
        val["associateId"] = ModelBase::toJson(m_AssociateId);
    }
    if(m_PlmnIsSet)
    {
        val["plmn"] = ModelBase::toJson(m_Plmn);
    }
    {
        nlohmann::json jsonArray;
        for( const auto& item : m_CellId )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            val["cellId"] = jsonArray;
        } 
    }
    if(m_TriggerIsSet)
    {
        val["trigger"] = ModelBase::toJson(m_Trigger);
    }
    

    return val;
}

void FilterCriteriaAssocTri::fromJson(const nlohmann::json& val)
{
    if(val.find("appInsId") != val.end())
    {
        setAppInsId(val.at("appInsId"));
    }
    if(val.find("associateId") != val.end())
    {
        if(!val["associateId"].is_null())
        {
            AssociateId newItem;
            newItem.fromJson(val["associateId"]);
            setAssociateId( newItem );
        }
        
    }
    if(val.find("plmn") != val.end())
    {
        if(!val["plmn"].is_null())
        {
            Plmn newItem;
            newItem.fromJson(val["plmn"]);
            setPlmn( newItem );
        }
        
    }
    {
        m_CellId.clear();
        if(val.find("cellId") != val.end())
        {
            for( const auto& item : val["cellId"] )
            {
                
                if(item.is_null())
                {
                    m_CellId.push_back( std::string() );
                }
                else
                {
                    std::string newItem;
                    newItem.fromJson(item);
                    m_CellId.push_back( newItem );
                }
                
            }
        }
    }
    if(val.find("trigger") != val.end())
    {
        if(!val["trigger"].is_null())
        {
            Trigger newItem;
            newItem.fromJson(val["trigger"]);
            setTrigger( newItem );
        }
        
    }
    
}


std::string FilterCriteriaAssocTri::getAppInsId() const
{
    return m_AppInsId;
}
void FilterCriteriaAssocTri::setAppInsId(std::string const& value)
{
    m_AppInsId = value;
    m_AppInsIdIsSet = true;
}
bool FilterCriteriaAssocTri::appInsIdIsSet() const
{
    return m_AppInsIdIsSet;
}
void FilterCriteriaAssocTri::unsetAppInsId()
{
    m_AppInsIdIsSet = false;
}
AssociateId FilterCriteriaAssocTri::getAssociateId() const
{
    return m_AssociateId;
}
void FilterCriteriaAssocTri::setAssociateId(AssociateId const& value)
{
    m_AssociateId = value;
    m_AssociateIdIsSet = true;
}
bool FilterCriteriaAssocTri::associateIdIsSet() const
{
    return m_AssociateIdIsSet;
}
void FilterCriteriaAssocTri::unsetAssociateId()
{
    m_AssociateIdIsSet = false;
}
Plmn FilterCriteriaAssocTri::getPlmn() const
{
    return m_Plmn;
}
void FilterCriteriaAssocTri::setPlmn(Plmn const& value)
{
    m_Plmn = value;
    m_PlmnIsSet = true;
}
bool FilterCriteriaAssocTri::plmnIsSet() const
{
    return m_PlmnIsSet;
}
void FilterCriteriaAssocTri::unsetPlmn()
{
    m_PlmnIsSet = false;
}
std::vector<std::string>& FilterCriteriaAssocTri::getCellId()
{
    return m_CellId;
}
bool FilterCriteriaAssocTri::cellIdIsSet() const
{
    return m_CellIdIsSet;
}
void FilterCriteriaAssocTri::unsetCellId()
{
    m_CellIdIsSet = false;
}
Trigger FilterCriteriaAssocTri::getTrigger() const
{
    return m_Trigger;
}
void FilterCriteriaAssocTri::setTrigger(Trigger const& value)
{
    m_Trigger = value;
    m_TriggerIsSet = true;
}
bool FilterCriteriaAssocTri::triggerIsSet() const
{
    return m_TriggerIsSet;
}
void FilterCriteriaAssocTri::unsetTrigger()
{
    m_TriggerIsSet = false;
}

}
}
}
}

