/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * HoStatus.h
 *
 * Description of the subscribed to event
 */

#ifndef HoStatus_H_
#define HoStatus_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of the subscribed to event
/// </summary>
class  HoStatus
    : public ModelBase
{
public:
    HoStatus();
    virtual ~HoStatus();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// HoStatus members


protected:
};

}
}
}
}

#endif /* HoStatus_H_ */
