/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineObject14.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_14::Inline_object_14()
{
    m_CaReConfSubscriptionIsSet = false;
    
}

Inline_object_14::~Inline_object_14()
{
}

void Inline_object_14::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_object_14::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_CaReConfSubscriptionIsSet)
    {
        val["CaReConfSubscription"] = ModelBase::toJson(m_CaReConfSubscription);
    }
    

    return val;
}

void Inline_object_14::fromJson(const nlohmann::json& val)
{
    if(val.find("CaReConfSubscription") != val.end())
    {
        if(!val["CaReConfSubscription"].is_null())
        {
            CaReConfSubscriptionPost newItem;
            newItem.fromJson(val["CaReConfSubscription"]);
            setCaReConfSubscription( newItem );
        }
        
    }
    
}


CaReConfSubscriptionPost Inline_object_14::getCaReConfSubscription() const
{
    return m_CaReConfSubscription;
}
void Inline_object_14::setCaReConfSubscription(CaReConfSubscriptionPost const& value)
{
    m_CaReConfSubscription = value;
    m_CaReConfSubscriptionIsSet = true;
}
bool Inline_object_14::caReConfSubscriptionIsSet() const
{
    return m_CaReConfSubscriptionIsSet;
}
void Inline_object_14::unsetCaReConfSubscription()
{
    m_CaReConfSubscriptionIsSet = false;
}

}
}
}
}

