/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineObject1.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_1::Inline_object_1()
{
    m_CellChangeSubscriptionIsSet = false;
    
}

Inline_object_1::~Inline_object_1()
{
}

void Inline_object_1::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_object_1::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_CellChangeSubscriptionIsSet)
    {
        val["CellChangeSubscription"] = ModelBase::toJson(m_CellChangeSubscription);
    }
    

    return val;
}

void Inline_object_1::fromJson(const nlohmann::json& val)
{
    if(val.find("CellChangeSubscription") != val.end())
    {
        if(!val["CellChangeSubscription"].is_null())
        {
            CellChangeSubscription newItem;
            newItem.fromJson(val["CellChangeSubscription"]);
            setCellChangeSubscription( newItem );
        }
        
    }
    
}


CellChangeSubscription Inline_object_1::getCellChangeSubscription() const
{
    return m_CellChangeSubscription;
}
void Inline_object_1::setCellChangeSubscription(CellChangeSubscription const& value)
{
    m_CellChangeSubscription = value;
    m_CellChangeSubscriptionIsSet = true;
}
bool Inline_object_1::cellChangeSubscriptionIsSet() const
{
    return m_CellChangeSubscriptionIsSet;
}
void Inline_object_1::unsetCellChangeSubscription()
{
    m_CellChangeSubscriptionIsSet = false;
}

}
}
}
}

