/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_201_4.h
 *
 * 
 */

#ifndef Inline_response_201_4_H_
#define Inline_response_201_4_H_


#include "ModelBase.h"

#include "RabEstSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_201_4
    : public ModelBase
{
public:
    Inline_response_201_4();
    virtual ~Inline_response_201_4();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_response_201_4 members

    /// <summary>
    /// 
    /// </summary>
    RabEstSubscription getRabEstSubscription() const;
    void setRabEstSubscription(RabEstSubscription const& value);
    bool rabEstSubscriptionIsSet() const;
    void unsetRabEstSubscription();

protected:
    RabEstSubscription m_RabEstSubscription;
    bool m_RabEstSubscriptionIsSet;
};

}
}
}
}

#endif /* Inline_response_201_4_H_ */
