/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_14.h
 *
 * 
 */

#ifndef Inline_object_14_H_
#define Inline_object_14_H_


#include "ModelBase.h"

#include "CaReConfSubscriptionPost.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_14
    : public ModelBase
{
public:
    Inline_object_14();
    virtual ~Inline_object_14();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_object_14 members

    /// <summary>
    /// 
    /// </summary>
    CaReConfSubscriptionPost getCaReConfSubscription() const;
    void setCaReConfSubscription(CaReConfSubscriptionPost const& value);
    bool caReConfSubscriptionIsSet() const;
    void unsetCaReConfSubscription();

protected:
    CaReConfSubscriptionPost m_CaReConfSubscription;
    bool m_CaReConfSubscriptionIsSet;
};

}
}
}
}

#endif /* Inline_object_14_H_ */
