/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200_6.h
 *
 * 
 */

#ifndef Inline_response_200_6_H_
#define Inline_response_200_6_H_


#include "ModelBase.h"

#include "MeasRepUeSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200_6
    : public ModelBase
{
public:
    Inline_response_200_6();
    virtual ~Inline_response_200_6();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_response_200_6 members

    /// <summary>
    /// 
    /// </summary>
    MeasRepUeSubscription getMeasRepUeSubscription() const;
    void setMeasRepUeSubscription(MeasRepUeSubscription const& value);
    
protected:
    MeasRepUeSubscription m_MeasRepUeSubscription;

};

}
}
}
}

#endif /* Inline_response_200_6_H_ */
