/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InlineResponse2009.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_9::Inline_response_200_9()
{
    
}

Inline_response_200_9::~Inline_response_200_9()
{
}

void Inline_response_200_9::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_response_200_9::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["RabRelSubscription"] = ModelBase::toJson(m_RabRelSubscription);
    

    return val;
}

void Inline_response_200_9::fromJson(const nlohmann::json& val)
{
    
}


RabRelSubscription Inline_response_200_9::getRabRelSubscription() const
{
    return m_RabRelSubscription;
}
void Inline_response_200_9::setRabRelSubscription(RabRelSubscription const& value)
{
    m_RabRelSubscription = value;
    
}

}
}
}
}

