/**
* RNI API
* The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_4.h
 *
 * 
 */

#ifndef Inline_object_4_H_
#define Inline_object_4_H_


#include "ModelBase.h"

#include "MeasTaSubscriptionPost.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_4
    : public ModelBase
{
public:
    Inline_object_4();
    virtual ~Inline_object_4();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Inline_object_4 members

    /// <summary>
    /// 
    /// </summary>
    MeasTaSubscriptionPost getMeasTaSubscription() const;
    void setMeasTaSubscription(MeasTaSubscriptionPost const& value);
    bool measTaSubscriptionIsSet() const;
    void unsetMeasTaSubscription();

protected:
    MeasTaSubscriptionPost m_MeasTaSubscription;
    bool m_MeasTaSubscriptionIsSet;
};

}
}
}
}

#endif /* Inline_object_4_H_ */
