/**
* BWM API
* The ETSI MEC ISG MEC015 Bandwidth Management API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "FixedBWPriority.h"

namespace llmec {
namespace mp2 {
namespace model {

FixedBWPriority::FixedBWPriority()
{
    
}

FixedBWPriority::~FixedBWPriority()
{
}

void FixedBWPriority::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const FixedBWPriority& o)
{
    j = nlohmann::json();
}

void from_json(const nlohmann::json& j, FixedBWPriority& o)
{
}


}
}
}

