/**
* BWM API
* The ETSI MEC ISG MEC015 Bandwidth Management API described using OpenAPI
*
* OpenAPI spec version: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RequestType.h
 *
 * Numeric value (0 - 255) corresponding to specific type of consumer
 */

#ifndef RequestType_H_
#define RequestType_H_


#include "ModelBase.h"


namespace org {
namespace llmec {
namespace mp2 {
namespace model {

/// <summary>
/// Numeric value (0 - 255) corresponding to specific type of consumer
/// </summary>
class  RequestType
    : public ModelBase
{
public:
    RequestType();
    virtual ~RequestType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// RequestType members


protected:
};

}
}
}
}

#endif /* RequestType_H_ */
