/**
* BWM API
* The ETSI MEC ISG MEC015 Bandwidth Management API described using OpenAPI
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* BwManagementApiImpl.h
*
* 
*/

#ifndef BW_MANAGEMENT_API_IMPL_H_
#define BW_MANAGEMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <BwManagementApi.h>

#include <pistache/optional.h>

#include "BwInfo.h"
#include "BwInfoDeltas.h"
//#include "Object.h"
#include <string>

namespace llmec {
namespace mp2 {
namespace api {

using namespace llmec::mp2::model;

class BwManagementApiImpl : public llmec::mp2::api::BwManagementApi {
public:
    BwManagementApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~BwManagementApiImpl() {}

    void bw_allocations_allocation_id_delete(const std::string &allocationId, Pistache::Http::ResponseWriter &response);
    void bw_allocations_allocation_id_get(const std::string &allocationId, Pistache::Http::ResponseWriter &response);
    void bw_allocations_allocation_id_patch(const std::string &allocationId, const BwInfoDeltas &bwInfoDeltas, Pistache::Http::ResponseWriter &response);
    void bw_allocations_allocation_id_put(const std::string &allocationId, const BwInfo &bwInfo, Pistache::Http::ResponseWriter &response);
    void bw_allocations_get(const Pistache::Optional<std::string> &appInsId, const Pistache::Optional<std::vector<std::string>> &applicationName, const Pistache::Optional<std::vector<std::string>> &sessionId, Pistache::Http::ResponseWriter &response);
    void bw_allocations_post(const BwInfo &bwInfo, Pistache::Http::ResponseWriter &response);

};

}
}
}



#endif
